// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdjiufcrirttivpwdeoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkaml1ZmNyaXJ0dGl2cHdkZW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTEyNzYsImV4cCI6MjA2NDc2NzI3Nn0.0QH_nf4HNXvS5KSKcoLLDYgZUQTXmOFf0COjJ-kqvAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);